### ISSUE TITLE
Error in 2.1.29

### ISSUE THREAD

**Issue by mnhende2** [HelenFoster/AnkiAddons#11]
@HelenFoster   Thanks for the great add on!  Unfortunately, it has stopped working in 2.1.29 (and I think 2.1.28 also, but I skipped that update).

Here is the debug info:

```
Debug info:
Anki 2.1.29 (bbff62bf) Python 3.8.0 Qt 5.14.1 PyQt 5.14.1
Platform: Windows 10
Flags: frz=True ao=True sv=1
Add-ons, last update check: 2020-07-31 04:52:58

Caught exception:
Traceback (most recent call last):
  File "aqt\taskman.py", line 87, in _on_closures_pending
  File "aqt\taskman.py", line 59, in <lambda>
  File "aqt\taskman.py", line 76, in wrapped_done
  File "aqt\sync.py", line 112, in on_future_done
  File "aqt\main.py", line 892, in on_collection_sync_finished
  File "aqt\main.py", line 684, in reset
  File "aqt\main.py", line 646, in moveToState
  File "aqt\main.py", line 653, in _deckBrowserState
  File "<C:\Program Files\Anki2129\decorator.pyc:decorator-gen-24>", line 2, in show
  File "lib\site-packages\anki\hooks.py", line 638, in decorator_wrapper
  File "lib\site-packages\anki\hooks.py", line 629, in repl
  File "aqt\deckbrowser.py", line 58, in show
  File "aqt\deckbrowser.py", line 115, in _renderPage
  File "aqt\deckbrowser.py", line 121, in __renderPage
  File "C:\Users\Admin-14\AppData\Roaming\Anki2\addons21\1836212767\__init__.py", line 121, in renderDeckTree
    nodes = [DeckNode(self.mw, node) for node in nodes]
TypeError: 'DeckTreeNode' object is not iterable
```

**Comment by HelenFoster** [comment]
Hi, thanks for letting me know! Unfortunately, looks like this is a major breakage, and I might need a bit longer to fix it.

**Comment by mnhende2** [comment]
Thanks for the update.  I'll keep it toggled off until then.  Wishing you a smoother and quicker fix to the problem that it seems it will take.
